# Generated by Django 2.0.2 on 2019-11-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
